name: flawfinder
on: [push]

jobs:
  build:
    env:
      working-directory: ./all-rules
    name: flawfinder-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flawfinder-action 
        uses: deep5050/flawfinder-action@master
